CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE personagem(
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    img VARCHAR(100) NOT NULL,
    jogo VARCHAR(255) NOT NULL
);